---
version: '2'

services:
  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPass
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
